REDIMIR/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('admin_panel.urls')),
    path('operador/', include('operador_panel.urls')),
    path('operadores/', include('operadores_crud.urls')),
    path('clientes/', include('clientes_crud.urls')),
    path('registros/', include('registros_crud.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes_crud/urls.py
from django.urls import path
from .views import clientes_crud, eliminar_cliente, cambiar_estado

urlpatterns = [
    path("", clientes_crud, name="clientes_crud"),
    path("eliminar/<int:cliente_id>/", eliminar_cliente, name="cliente_eliminar"),
    path("cambiar_estado/<int:cliente_id>/", cambiar_estado, name="cambiar_estado",)
]

clientes_crud/models.py
from django.db import models

class Cliente(models.Model):
    nombre = models.CharField(max_length=30)
    correo = models.EmailField(unique=True)
    telefono = models.IntegerField()
    estado = models.BooleanField(default=True, blank=True)
    imagen = models.ImageField(
        upload_to='img/cliente/',
        blank=True,
        null=True,
        default='img/cliente/default.png')

class UbicacionCl(models.Model):
    idCliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    numero = models.IntegerField()
    calle = models.CharField(max_length=30)

clientes_crud/forms.py
from django import forms
from .models import *

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        exclude = ['estado']


class UbicacionForm(forms.ModelForm):
    class Meta:
        model = UbicacionCl
        fields = '__all__'

clientes_crud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from admin_panel.utils import admin_required
from django.http import FileResponse
from .models import *
from .forms import *

@admin_required
def clientes_crud(request):
    clientes_info = Cliente.objects.order_by('nombre')
    form_cliente = ClienteForm()
    form_ubicacion = UbicacionForm()

    if request.method == 'POST':
        if 'submit_cliente' in request.POST:
            form_cliente = ClienteForm(request.POST, request.FILES)
            if form_cliente.is_valid():
                form_cliente.save()
                #messages.success(request,f'Cliente “{Cliente.nombre}” generado correctamente.')
                return redirect('clientes_crud')
            else:
                print("Error al generar cliente.")
                messages.error(request, "Error al generar cliente.")
                print(form_cliente.errors)
        
        elif 'submit_ubicacion' in request.POST:
            form_ubicacion = UbicacionForm(request.POST)
            if form_ubicacion.is_valid():
                form_ubicacion.save()
                #messages.success(request,f'Ubicacion “{UbicacionCl.calle}” generado correctamente.')
                return redirect('clientes_crud')
            else:
                messages.error(request, "Error al generar ubicacion.")
                print(form_ubicacion.errors)

    return render(request, "clientes_crud/clientes.html", {
        "active": "clientes",
        'clientes_info': clientes_info, 
        })

@admin_required
def eliminar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    cliente.delete()
    return redirect('clientes_crud')

@admin_required
def cambiar_estado(request, cliente_id):
    if request.method == 'POST':
        cliente = get_object_or_404(Cliente, id=cliente_id)
        cliente.estado = not cliente.estado
        cliente.save()
        return JsonResponse({
            'success': True,
            'id': cliente.id,
            'nombre': cliente.nombre,
            'correo': cliente.correo,
            'telefono': cliente.telefono,
            'estado': cliente.estado
        })
    return JsonResponse({'success': False}, status=405)

templates/clientes_crud/clientes.html
{% extends "admin_panel/navbar_admin.html" %}
{% load static %}

{% block title %}Panel AdministradorREDIMIR{% endblock %}

{# ➊ CSS extra específico de este panel #}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/clientes.css' %}">
<script src="{% static 'js/clientes.js' %}"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
{% endblock %}

{% block main %}
<h1 class="mb-4 text-dark">Gestion Clientes</h1>

<!-- =====  tarjetas resumen  ===== -->
<div class="card mt-4">
  <div class="card-body">
    <div class="row">
      <div class="col-md-6 border-end">
        <h5 class="card-title mb-3">Generar Cliente</h5>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input type="text" class="form-control" name="nombre" required />
            </div>
            <div class="row g-3">
            <div class="col-md-6">
                <label class="form-label">Correo</label>
              <input type="email" class="form-control" name="correo" required/>
            </div>
            <div class="col-md-6">
                <label class="form-label">Telefono</label>
                <input type="number" class="form-control" name="telefono"/>
            </div>
            <div class="col-12">
              <label class="form-label">Imagen (Opcional)</label>
              <input type="file" class="form-control" name="imagen"/>
            </div>
            <div class="col-12 text-end">
              <button type="submit" name="submit_cliente" class="btn btn-success btn-opcion">Registrar Cliente</button>
            </div>
          </div>
        </form>
      </div>
      <!-- Asignar Ubicación -->
      <div class="col-md-6">
        <h5 class="card-title mb-3">Asignar Ubicación</h5>
        <form method="POST">
          {% csrf_token %}
          <div class="mb-3">
            <label class="form-label">Cliente</label>
            <select name="idCliente" id="id_idCliente" class="form-select">
              {% for cliente in clientes_info %}
              <option value="{{ cliente.id }}">{{ cliente.nombre }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="mb-3">
            <label class="form-label">Nombre de la calle</label>
            <input type="text" class="form-control" id="id_calle" name="calle" maxlength="30" required />
          </div>
          <div class="mb-3">
            <label class="form-label">Número</label>
            <input type="number" class="form-control" id="id_numero" name="numero" required />
          </div>
          <div class="text-end">
            <button type="submit" class="btn btn-success btn-opcion" name="submit_ubicacion">Asignar Ubicación</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="card mt-4">
  <div class="card-body">
    <h5 class="card-title">Lista de Clientes</h5>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Correo</th>
            <th>telefono</th>
            <th>Ver Ubicaciones</th>
            <th>Estado</th>
            <th>Eliminar</th>
            <th>Ver Perfil</th>
          </tr>
        </thead>
        <tbody>
            {% for cl in clientes_info %}
            <tr id="fila-{{ cl.id }}">
                <td>{{ cl.nombre }}</td>
                <td>{{ cl.correo }}</td>
                <td>{{ cl.telefono }}</td>
                <td><a href="" class="btn btn-success">En desarollo</a></td>
                <td>
                  <button 
                  id="btn-estado-{{ cl.id }}" 
                  class="btn {% if cl.estado %}btn-success{% else %}btn-danger{% endif %}" 
                  onclick="cambiarEstado('{{ cl.id }}')">
                  {% if cl.estado %}Activo{% else %}Bloqueado{% endif %}
                </button>
                </td>
                <td>
                  <a href="{% url 'cliente_eliminar' cl.id %}" class="btn btn-danger" onclick="return confirm('¿Seguro que deseas eliminar este cliente?');"><i class="bi bi-trash" style="font-size: 1.1rem;"></i></a>
                </td>
                <td>
                  <button class="btn btn-success">En desarollo</button>
                </td>
              </tr>
              {% empty %}
              <tr><td colspan="7" class="text-center">Sin Clientes aun aún.</td></tr>
              {% endfor %}
            </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}